version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run site health checks
          command: yarn test

workflows:
  build:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
